version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - vayunx-core-ui
      - vayunx-discovery-service
  vayunx-core-ui:
    image: vayunx-core-ui
    expose:
      - "80"
    volumes:
      - ./custom-env.js:/usr/share/nginx/html/env-config.js
    depends_on:
      - vayunx-discovery-service

  vayunx-discovery-service:
    image: vayunx-discovery-service
    expose:
      - "8000"


