version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/demo.vayunx.com/fullchain.pem:/etc/letsencrypt/live/demo.vayunx.com/fullchain.pem
      - /etc/letsencrypt/live/demo.vayunx.com/privkey.pem:/etc/letsencrypt/live/demo.vayunx.com/privkey.pem
    ports:
      - "443:443"
    depends_on:
      - vayunx-core-ui
      - vayunx-discovery-service
      - vayunx-core-backend

  vayunx-core-ui:
    image: 168varun/vayunx-core-ui:latest
    expose:
      - "80"
    volumes:
      - ./custom-env.js:/usr/share/nginx/html/env-config.js
    depends_on:
      - vayunx-discovery-service
      - vayunx-core-backend

  vayunx-discovery-service:
    image: 168varun/vayunx-discovery-service:latest
    expose:
      - "8000"

  vayunx-core-backend:
    image: 168varun/vayunx-core-backend:latest
    expose:
      - "8081"


